컴포넌트 분리 및 모킹된 api 적용 완료
bh2980/FE1-Stock-Project pull request #4
Opened 2022-07-10 05:07 UTC by bh2980

각 컴포넌트 분리하고 모킹된 api로 적용했습니다.

TODO Tree에 CHECK 태크를 추가했습니다.
확인해볼 부분이랑 표시하려고 임시로 loading 되어있는 부분 표시해놨으니 
추가하시고 체크 부탁드려요.

2022-07-10 07:21 UTC, kasterra requested changes

2022-07-10 07:21 UTC, kasterra commented on src/assets/dummy.js
> +// TODO 이장훈: Interval 별 차트 데이터 삽입 필요
?? 이것은 무슨 의미인가요? 나중에 하겠다는 뜻일까요???

2022-07-10 07:21 UTC, kasterra commented on src/components/Company/DashBoard.jsx
> +		const logo = await getStockProfile(ticker, token);
굳이 변수를 만들어 넣는것보다 그냥 함수에 넣으면 안될까요? `token` 변수가 이곳말고는 이 파일 내에서 쓰이지 않는것 같습니다.

2022-07-10 07:21 UTC, kasterra commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
지금 코드가 verbose 하다고 생각이 드셔서 이렇게 적어놓으신걸까요?

2022-07-10 07:21 UTC, kasterra commented on src/components/Company/RecommendList.jsx
> +	let history = useHistory();
let 을 사용하신 이유가 있나요? 불변성을 중요시하는 리액트 특성상 꼭 필요한곳이 아닌, 특히 컴포넌트 내에서는 let의 사용은 최대한 지양됩니다. 변해야 할 상태라면 상태 관리 매커니즘을 이용해서 관리해 주세요

2022-07-10 07:21 UTC, kasterra commented on src/components/Home/IndexList.jsx
> +		//TODO 이장훈 : 임시로 데이터 잘라서 표현 중 -> 주기적으로 돌도록 수정할 것.
PR을 올렸는데 왜 TODO가 같이 올라오나..요? 마감 기한 늘려도 좋으니 TODO 완료하시고 PR 부탁드립니당

2022-07-10 07:21 UTC, kasterra commented on src/mockAxios.js
> -mock.onGet('/api/yh/market/v2/get-summary').reply(config => {
아 혹시 이거 앞에 / 있으면 정상작동 안하나요?

2022-07-10 07:21 UTC, kasterra commented on src/pages/Company/Company.jsx
> +import React from 'react';
혹시 이 구문 없으면 린터에러가 뜨나요? 뜨면 그대로 냅두고, 안뜨면 날려버리는게 어떨까요

2022-07-10 13:31 UTC, bh2980 commented on src/assets/dummy.js
> +// TODO 이장훈: Interval 별 차트 데이터 삽입 필요
네 일단 저는 근시일내에 처리해야할 작업들에 TODO 적어놓는 쪽으로 사용했습니다.
혹시 다른 의미로 넣어두신건가요??

2022-07-10 13:33 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
네, 지금 그 부분이 api에서 호출하는 부분들인데 
{ data }로 변수가 중복되어서 어떻게 처리하면 좋을지 생각해보고 있었거든요.
하나의 함수 안에서 적으려니 중복이 생겨서 어떻게하면 깔끔하게 적을 수 있을까 생각해보려고 적어놨습니다.

2022-07-10 13:33 UTC, bh2980 commented on src/components/Company/RecommendList.jsx
> +	let history = useHistory();
예제 따라했습니당.......수정할게용.........
최대한 const로 사용해야한다는 거 알아갑니다!

2022-07-10 13:35 UTC, bh2980 commented on src/components/Home/IndexList.jsx
> +		//TODO 이장훈 : 임시로 데이터 잘라서 표현 중 -> 주기적으로 돌도록 수정할 것.
아 젤 위에 TODO 처럼 이부분은 근시일내에 작업할 예정이고 까먹을까봐 적어놓았습니다.
현재 브랜치가 컴포넌트로 나누고 모킹된 api 적용하는게 목적인 브랜치인데
저 부분은 기능적으로 다른 부분이라 따로 브랜치 만들어서 작업해야할 것 같아서요.

2022-07-10 13:38 UTC, kasterra commented on src/assets/dummy.js
> +// TODO 이장훈: Interval 별 차트 데이터 삽입 필요
맞습니다. TODO 사항을 resolve 해달라는 뜻이었는데용.

2022-07-10 13:38 UTC, kasterra commented on src/components/Home/IndexList.jsx
> +		//TODO 이장훈 : 임시로 데이터 잘라서 표현 중 -> 주기적으로 돌도록 수정할 것.
넹 알겠습니다

2022-07-10 13:39 UTC, bh2980 commented on src/mockAxios.js
> -mock.onGet('/api/yh/market/v2/get-summary').reply(config => {
@kasterra 
아뇨. 있어도 잘 작동합니다.
수정한 이유가 처음에 제대로 응답을 못 받아오길래 뭐가 문제지 하고 수정해보다가
저 api만 /가 붙어있길래 혹시나해서 수정해봤습니다.
다시 복구해 놓을까요?

2022-07-10 13:40 UTC, kasterra commented on src/mockAxios.js
> -mock.onGet('/api/yh/market/v2/get-summary').reply(config => {
다른거랑 통일성 있게 / 뗍시다.

2022-07-10 13:41 UTC, bh2980 commented on src/pages/Company/Company.jsx
> +import React from 'react';
@kasterra 
import React from 'react' 구문 말씀하시는거죠?
날려도 정상적동합니다. 날리겠습니다.

2022-07-10 13:41 UTC, kasterra commented on src/components/Company/RecommendList.jsx
> +	let history = useHistory();
수정하시고 이 이슈 resolve 처리 해주시면 됩니다.

2022-07-10 13:41 UTC, kasterra commented on src/pages/Company/Company.jsx
> +import React from 'react';
넹. React17 부터 저거 없어도 컴파일이 잘 되걸랑요

2022-07-10 13:44 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		const logo = await getStockProfile(ticker, token);
@kasterra 
token 변수를 빼고 const logo = await getStockProfile(ticker, process.env.~~~); 말씀하시는건가요??

2022-07-10 13:44 UTC, kasterra commented on src/components/Company/DashBoard.jsx
> +		const logo = await getStockProfile(ticker, token);
네

2022-07-10 13:46 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		const logo = await getStockProfile(ticker, token);
@kasterra 네 수정하겠습니다.

2022-07-10 13:48 UTC, bh2980 commented on src/mockAxios.js
> -mock.onGet('/api/yh/market/v2/get-summary').reply(config => {
@kasterra 넴

2022-07-10 13:50 UTC, bh2980 commented on src/assets/dummy.js
> +// TODO 이장훈: Interval 별 차트 데이터 삽입 필요
@kasterra 아 그러면 이번주 일요일까지 인터벌 추가하고 다시 멘션드리면 될까요??

2022-07-10 13:52 UTC, kasterra commented on src/assets/dummy.js
> +// TODO 이장훈: Interval 별 차트 데이터 삽입 필요
음.. 일단 이거 빼고 머지 하시고, 인터벌 추가하는건 다른 브랜치로 팝시당

2022-07-10 13:53 UTC, bh2980 commented on src/assets/dummy.js
> +// TODO 이장훈: Interval 별 차트 데이터 삽입 필요
@kasterra 네 알겠습니당.

2022-07-10 13:55 UTC, kasterra commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
음... 코드 확인해 봤는데, dashboard 종류가 여러개잖아요 각각의 dashboard내에서 fetch 해와도 될거 같은데 굳이 부모에서 fetching 해와서 자식에게 넘겨줄 필요가 있나요? 각 컴포넌트에서 fetch 하면 안되나요...?

2022-07-10 14:15 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
@kasterra 
네 저도 그렇게 처리하는게 좀 더 깔끔하지 않을까 했는데
좀 애매했던 부분이 getStockSummary라는 한개의 api에서 재무, 어닝, 회사정도, 추천 트렌드가 다 들어있어서
이를 각 대시보드로 내리게 되면 한번 fetch할걸 4번 중복으로 fetch하는 셈이 되더라구요.
그래서 일단 부모 쪽에 넣어놨습니다. 밑으로 내리는게 나을까요??

2022-07-10 14:17 UTC, kasterra commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
react-query가 caching 처리를 해준다는것을 기억 하시나요? 한번 fetch 하고, fresh한 시간 이내에서는 다시 fetch를 하지 않고, cached된 데이터를 그대로 사용한답니다~

2022-07-10 14:20 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
@kasterra 
충격적...!
아 근데 내려고 로고를 불러오는 api랑 getStockSummary api가 똑같이 { data }라는 변수로 불러와져서
중복이 발생하긴 하거든요. 이 부분은 어떻게 처리하는게 좋을까요??

개인적으로는 로고 하나 불러오려고 쓰는게 좀 그렇기도 하고 
로고 표시 UI가 완성도가 낮아서 좀 그런데 그냥 로고 빼버릴까요?

2022-07-10 14:22 UTC, kasterra commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
로고 표시 UI? 어느쪽 부분이지요? 중복이 발생한다면 alias를 지정해 줘야겠죠 네

2022-07-10 14:25 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
@kasterra 
대시보드에서 회사 정보 표시할 때 가장 위에 원 안에 로고 이미지 넣는 부분이요.
로고 이미지가 있는 편이 낫지않을까해서 넣긴 했는데 어떻게 해도 이상하더라구요.

2022-07-10 14:35 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
하긴 이 부분은 지금 중요한기 아니니까 나중에 생각하는게 낫겠네요.
일단 내일 각 대시보드 별로 fetch하도록 수정하겠습니다.

2022-07-11 13:37 UTC, bh2980 commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
@kasterra 수정했습니당. 머지하면 될까요??

2022-07-11 13:38 UTC, kasterra commented on src/components/Company/DashBoard.jsx
> +		//TODO 이장훈 : logo, news 어떻게 해야 깔끔하게 할 수 있을까?
LGTM

2022-07-11 13:40 UTC, merged